Use cmake build command wrapper, and add iOS build
binary1248/SFML-Buildbot pull request #10
Opened 2018-01-09 23:35 UTC by JonnyPtn

I've added the iOS build, tested on my machine (macOS 10.13, Xcode 9) running the same version of buildbot.

This also removes the dependency on makefile generators and uses the cmake build command, so adding extra generators will hopefully be easier in future.

I should probably mention Python isn't my first language and iOS isn't my first platform, but hopefully this helps in some way.

2018-01-13 11:33 UTC, mantognini commented
This looks good. 👍

2018-01-13 16:35 UTC, binary1248 approved these changes

2018-01-15 23:26 UTC, eXpl0it3r commented
I'd still say to reuse the existing slave that's already on the Mac Mini, otherwise we'd have to run two slaves on the same machine and who knows if that causes trouble.

2018-01-15 23:39 UTC, JonnyPtn commented
Done (I think...)

2018-01-15 23:44 UTC, eXpl0it3r approved these changes

2018-01-15 23:47 UTC, binary1248 requested changes

2018-01-15 23:47 UTC, binary1248 commented on buildslaves.py
> +    ]
Let's not touch this file if we don't have to shall we? :wink:

2018-01-16 22:25 UTC, binary1248 approved these changes

2018-01-24 23:58 UTC, eXpl0it3r commented
What's the status on this?

@binary1248 Do you need anything special or just a question of a free time slot?
@mantognini Do you think the CI needs some adjustments first?

2018-01-24 23:59 UTC, binary1248 commented
Might give this a try this coming weekend... more time to recover if something goes wrong.

2018-01-27 18:28 UTC, merged